# Generated by Django 4.2.4 on 2023-08-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reservation',
            new_name='reservation_detail',
        ),
    ]
