# Generated by Django 4.2.4 on 2023-08-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_reservation_reservation_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='reservation_detail',
            name='table',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation_detail',
            name='timing',
            field=models.CharField(default='', max_length=50),
        ),
    ]
