# Generated by Django 4.2.4 on 2023-08-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_detail_reservation_detail_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation_detail',
            name='table',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation_detail',
            name='timing',
            field=models.CharField(max_length=50),
        ),
    ]
