# Generated by Django 4.2.4 on 2023-08-22 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_food_name_alter_reservation_detail_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_detail',
            name='booking_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation_detail',
            name='booking_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Indian', 'India'), ('Italian', 'Itli'), ('Other', 'Other')], max_length=20),
        ),
    ]
