# Generated by Django 4.2.4 on 2023-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='default_food.jpg', upload_to='food_pics'),
        ),
    ]
