# Generated by Django 4.2.4 on 2023-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_timings_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_id',
            field=models.CharField(default='idli123', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
