# Generated by Django 4.2.4 on 2023-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_food_food_id_alter_cart_quantity_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(default='0.6938876938615378', max_length=100, unique=True),
        ),
    ]
