# Generated by Django 4.2.4 on 2023-08-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_food_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_id',
        ),
    ]
