# Generated by Django 4.2.4 on 2023-08-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_food_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
