# Generated by Django 4.2.4 on 2023-08-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_food_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
