# Generated by Django 4.2.4 on 2023-08-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_cart_usercart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='food_item',
        ),
    ]
