# Generated by Django 4.2.4 on 2023-08-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_fooditem_food_id'),
        ('users', '0006_alter_usercart_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='food_item',
            field=models.ManyToManyField(to='restaurant.fooditem'),
        ),
    ]
