# Generated by Django 4.2.4 on 2023-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userorder_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='food_item',
        ),
        migrations.AddField(
            model_name='usercart',
            name='food_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='usercart',
            name='food_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
