# Generated by Django 4.2.4 on 2023-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usercart_food_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='items',
        ),
        migrations.AddField(
            model_name='userorder',
            name='items',
            field=models.TextField(default=''),
        ),
    ]
